/// Flutter icons Customicon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Customicon
///      fonts:
///       - asset: fonts/Customicon.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Customicon {
  Customicon._();

  static const _kFontFam = 'Customicon';
  static const _kFontPkg = null;

  static const IconData droplet = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_sleep = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData droplets = IconData(0xe9aa, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shower = IconData(0xf2cc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toilet_paper = IconData(0xf71e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_showers_heavy = IconData(0xf740, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toilet = IconData(0xf7d8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
